# -*- coding: utf-8 -*-
"""aula_04.03.24_listas_tuplas_dicionarios

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hHUQIJmzgljnzMaXIZ__K1rW0TZuYt1N

1 - Ler uma lista de 5 números inteiros e mostre cada número juntamento com a sua posição na lista.
"""

lista = [-7, 2, 20, -4,5]
i = 0
while i < len(lista):
  print(f'{i} : {lista[i]}')
  i += 1

lista = [-7, 2, 20, -4,5]
i = 0

for item in lista:
  print(f'{i}: {item}')
  i += 1

lista = [-7, 2, 20, -4,5]
i = 0
for idx, item in enumerate(lista):
  print(f'{idx}: {item}')

"""2 -  Ler uma lista de 10 números reais e mostre-os na ordem inversa que foram lidos."""

lista = [16, -5, 2, 3.14, 25/123, -2, 3/6, 0, 2, 1, 8]
print(lista[::-1])

"""3 - Ler uma lista com 5 idades e exibir a maior e a menor"""

idade = [26, 27, 18, 18, 45, 34]
print(f'A maior idade é {max(idade[::])} e a menor idade é {min(idade[::])}')

"""4 - Inicialize uma lista de 10 números inteiros. Armazene os números pares em uma lista PAR e os números ímpares em uma lista ÍMPAR:"""

n = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
n_pares =  [x for x in n if x % 2 == 0]
n_impares = [x for x in n if x % 2 != 0]
print(n_pares)
print(n_impares)

"""5. Escreva um programa que troque o primeiro com o último
elemento de uma lista qualquer.
"""

lista = list(range(10))
lista = lista[-1:] + lista[1:len(lista)-1] + lista[:1]
print(lista)

"""6. Qual a saída/resultado da seguinte compreensão de lista?"""

[[1 + j*3 + i for i in range(3)] for j in range(3)]

"""7. Considere que você recebe um dicionário contendo informações sobre produtos em
uma loja. Cada chave do dicionário é o nome de um produto e cada valor é uma tupla
contendo o preço e a quantidade em estoque desse produto.
"""

produtos = {
    'caneta': (1.99,  100),
    'papel': (0.50,  30),
    'tesoura':(3.75,  223),
    'borracha':(2.50,  12)
}

while True:
  p_max = float(input('Entre com o valor máximo R$: '))
  if p_max == 0:
    break
  #print(p_max)
  for prod in produtos:
    preco = produtos[prod][0]
    if preco <= p_max:
      print(prod, preco)

"""8. Em uma competição de ginástica, cada atleta recebe votos de
sete jurados. A melhor e a pior nota são eliminadas. A sua nota fica
sendo a média dos votos restantes. Você deve fazer um programa
que receba o nome do ginasta e as notas dos sete jurados
alcançadas pelo atleta em sua apresentação e depois informe a sua
média, conforme a descrição acima informada (retirar o melhor e o
pior salto e depois calcular a média com as notas restantes). As
notas não são informadas em ordem crescente ou decrescente.
"""

'''n_atletas = float(input('Digite o número de atletas na competição: '))
atleta_a = input(f'Digite o nome do atleta: ')
nota_atleta_a = []
for n in range(7):
  nota_atleta_a.append(float(input(f'Digite a {n+1}ª nota do atleta: ')))
nota_atleta_a.remove(len(nota_atleta_a))
nota_atleta_a.pop(0)
media_atleta_a = sum(nota_atleta_a)/len(nota_atleta_a)

print(f'A média do atleta é {media_atleta_a}')'''





nome = input('Nome do ginasta: ')
notas = []
cont = 0
njurados = 7
while cont < njurados:
  nota = float(input(f'nota {cont+1}: '))
  notas.append(nota)
  cont += 1
print(notas)
notas.sort()
print(notas)
notas_finais = notas[1: -1]
print(notas_finais)
media = sum(notas_finais)/len(notas_finais)
print(f'Ginasta {nome}: nota {media}')

